version: '3'

services:
    ctf:
        restart: always
        build:
            context: .
            dockerfile: ./build/Dockerfile
        read_only: true
        ports:
            - '40007:40007'
